development:
  adapter: postgresql
  database: ic-2048-development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ic-2048-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ic-2048-production
  pool: 5
  timeout: 5000